### ISSUE TITLE
New example with hooks instead of mappings.

### ISSUE THREAD

**Issue by benjamin-heasly** [RenderToolbox/RenderToolbox4#21]
Hi @tlian7 @hblasins @DavidBrainard @wandell.

We spoke recently about working on a new example that will address some confusing aspects of RenderToolbox4, especially around "remodeler" hook functions vs mappings.

If you're game, I'd like to manage that work with this issue.  I propose:
 - you could make a branch with the scene and script you have so far
 - I could check it out and help with debugging and commenting
 - we could iterate like that a few times
 - when we all like the example, we could make a PR and merge the branch into master

How does that sound?

**Comment by tlian7** [comment]
Hi @benjamin-heasly,

This sounds like a great idea. I've done the following:

1. Created a branch in RTB4 called [MoreExampleScenes](https://github.com/RenderToolbox/RenderToolbox4/tree/MoreExampleScenes).
2. Added three example scenes that I've been working on:
- [SponzaAtrium](https://github.com/RenderToolbox/RenderToolbox4/tree/MoreExampleScenes/ExampleScenes/MakeSponzaAtrium): Renders an atrium with different area light spectra and different camera types. 
- [CrytekSponza](https://github.com/RenderToolbox/RenderToolbox4/tree/MoreExampleScenes/ExampleScenes/MakeCrytekSponza): Renders a fancier version of the atrium at three different camera positions. 
- [MaskAndBumpTest](https://github.com/RenderToolbox/RenderToolbox4/tree/MoreExampleScenes/ExampleScenes/MakeMaskAndBumpTest): Renders a simple vase in order to test the changes I've made in mPbrt that recognize opacity/mask textures and bump maps.

For the most part these scenes render for me and do the various things that I want them to do (i.e. move the camera around, rotate the light, etc.) but it would be nice to know if they render for you and if the workflow makes sense. **Note: These scenes require the changes I made in [a separate branch of mPbrt](https://github.com/RenderToolbox/mPbrt/tree/moreTextureOptions) in order to read in the opacity and bump maps from the OBJ files.** 

I believe that @hblasins also has a few scenes he would like to share.

**Comment by hblasins** [comment]
Hi @benjamin-heasly, @tlian7 

I've added a scene of my own (Car) to the branch MoreExampleScenes. This model uses .TAG files, which you can now convert to .EXR if you checkout **mPbrt branch exrFix**, where I added this functionality.

In this example I'm trying to render a car with and without the taillights on. Unfortunately however promotion to area lights in PBRT does not work for both taillights, one seems to be fine but the other is no. I think the problem lies in some of the surface normals being flipped. I don't know when and how this is happens, as the mesh imported into Blender looks OK.

**Comment by benjamin-heasly** [comment]
@tlian7 @hblasins -- Sweet.  These should be nice.

So I think the first thing we should do is resolve your pull requests in the other repos.  That will make it easier to play along here and try things out.

I'll go to the other repos now and make some comments.
