### ISSUE TITLE
Missing struct2xml.m

### ISSUE THREAD

**Issue by hblasins** [RenderToolbox/RenderToolbox4#29]
Perhaps this file could be included in the distribution?

**Comment by benjamin-heasly** [comment]
Hi @hblasins,

`struct2xml` is on the file exchange, [here](https://www.mathworks.com/matlabcentral/fileexchange/28639-struct2xml).

I feel strongly that the way to deal with dependencies like this is with a dependency management tool, ie ToolboxToolbox, rather than duplicating them inside the project repo.  If you deploy RenderToolbox4 with ToolboxToolbox, struct2xml will be downloaded and added to the path automatically.

That said, struct2xml is pretty small.  If you want to make  PR that includes struct2xml in a folder like `Utilities/External`, I'd be willing to accept it.

**Comment by tlian7** [comment]
Hi @benjamin-heasly and @hblasins 

I also had this problem too, and discovered that struct2xml was located in Psychtoolbox...which is kind of like a soft requirement I suppose for RTB4. It did take me a while to find it though so perhaps we should put it into the actual RTB4 repo somewhere.

**Comment by benjamin-heasly** [comment]
It's in!
